# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  ports:
    - port: {{ .Values.neo4j.ports.http }}
      targetPort: 7474
      name: http
    - port: {{ .Values.neo4j.ports.bolt }}
      targetPort: 7687
      name: bolt
  selector:
    app: neo4j
