# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

image:
  repository: opea/graphrag-ui
  tag: "latest"

containerPort: 5173

LLM_MODEL_ID: "meta-llama/Meta-Llama-3-8B-Instruct"
